### PR TITLE
[FIX] HTML close tag

### PR DESCRIPTION
**Pull request by omrilotan**
@cwjohan HTML close tag was just `<html>` instead of `</html>`

### CODE REVIEW

**Comment by cwjohan** [comment]
Thanks for pointing out the closing HTML tag problem, Omri.

**Comment by omrilotan** [comment]
Thanks, Craig. Do you think you'll merge it?

**Comment by cwjohan** [comment]
Yes. Just extremely busy with other things just now.

**Comment by cwjohan** [comment]
Fix for html closing tag.

**Pull request merged**
